name: CD

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cd:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y pandoc
      - run: make
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - id: deployment
        uses: actions/deploy-pages@v4
